using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using ExampleAPI.Installers;
using ExampleAPI.Options;
using ExampleAPI.Services;
using FluentAssertions;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.IdentityModel.Tokens;
using Xunit;

namespace ExampleAPI.Tests.Services
{
    /// <summary>
    /// Verifies that tokens generated by other systems (wrong issuer, wrong audience,
    /// or wrong signing key) are rejected by our configured TokenValidationParameters.
    /// Acceptance criterion: "Tokens from other systems are rejected" (US-EX-24).
    /// </summary>
    public class JWTForeignTokenRejectionTests
    {
        private readonly TokenValidationParameters _validationParams;
        private readonly JWTService _service;

        public JWTForeignTokenRejectionTests()
        {
            var config = new ConfigurationBuilder()
                .AddInMemoryCollection(new Dictionary<string, string>
                {
                    { "JwtSettings:Secret", "OurSecretKeyThatIsLongEnoughForHmacSha512Algorithm!!" },
                    { "JwtSettings:Issuer", "OurAPI" },
                    { "JwtSettings:Audience", "OurAPI" },
                    { "JwtSettings:TokenLifetime", "01:00:00" }
                })
                .Build();

            // Use the real JWTInstaller to wire up services exactly as production does
            var services = new ServiceCollection();
            var installer = new JWTInstaller();
            installer.InstallServices(services, config);

            var provider = services.BuildServiceProvider();
            _validationParams = provider.GetRequiredService<TokenValidationParameters>();
            _service = provider.GetRequiredService<JWTService>();
        }

        [Fact]
        public void OurToken_IsAccepted()
        {
            var user = new ExampleAPI.Contracts.Shared.LoggedinUser
            {
                Username = "testuser",
                Email = "test@example.com",
                UserID = Guid.NewGuid()
            };

            var token = _service.GenerateJSONWebToken(user);

            var handler = new JwtSecurityTokenHandler();
            var principal = handler.ValidateToken(token, _validationParams, out _);
            principal.Should().NotBeNull();
        }

        [Fact]
        public void Token_WithWrongSigningKey_IsRejected()
        {
            var foreignToken = CreateForeignToken(
                secret: "CompletelyDifferentSecretKeyFromAnotherSystemLongEnough!!",
                issuer: "OurAPI",
                audience: "OurAPI");

            var handler = new JwtSecurityTokenHandler();
            var act = () => handler.ValidateToken(foreignToken, _validationParams, out _);

            act.Should().Throw<SecurityTokenSignatureKeyNotFoundException>();
        }

        [Fact]
        public void Token_WithWrongIssuer_IsRejected()
        {
            // Same signing key but different issuer — simulates a token from another
            // service that happens to share the key but is not the expected issuer
            var foreignToken = CreateForeignToken(
                secret: "OurSecretKeyThatIsLongEnoughForHmacSha512Algorithm!!",
                issuer: "ForeignSystem",
                audience: "OurAPI");

            var handler = new JwtSecurityTokenHandler();
            var act = () => handler.ValidateToken(foreignToken, _validationParams, out _);

            act.Should().Throw<SecurityTokenInvalidIssuerException>();
        }

        [Fact]
        public void Token_WithWrongAudience_IsRejected()
        {
            var foreignToken = CreateForeignToken(
                secret: "OurSecretKeyThatIsLongEnoughForHmacSha512Algorithm!!",
                issuer: "OurAPI",
                audience: "SomeOtherService");

            var handler = new JwtSecurityTokenHandler();
            var act = () => handler.ValidateToken(foreignToken, _validationParams, out _);

            act.Should().Throw<SecurityTokenInvalidAudienceException>();
        }

        [Fact]
        public void Token_WithWrongIssuerAndAudience_IsRejected()
        {
            var foreignToken = CreateForeignToken(
                secret: "OurSecretKeyThatIsLongEnoughForHmacSha512Algorithm!!",
                issuer: "ForeignIssuer",
                audience: "ForeignAudience");

            var handler = new JwtSecurityTokenHandler();
            var act = () => handler.ValidateToken(foreignToken, _validationParams, out _);

            act.Should().Throw<SecurityTokenException>();
        }

        [Fact]
        public void Token_WithNoExpiration_IsRejected()
        {
            // Create a token without an expiration claim
            var key = new SymmetricSecurityKey(
                Encoding.ASCII.GetBytes("OurSecretKeyThatIsLongEnoughForHmacSha512Algorithm!!"));
            var credentials = new SigningCredentials(key, SecurityAlgorithms.HmacSha512);
            var token = new JwtSecurityToken(
                issuer: "OurAPI",
                audience: "OurAPI",
                claims: new[] { new Claim("Username", "test") },
                expires: null,
                signingCredentials: credentials);
            var tokenString = new JwtSecurityTokenHandler().WriteToken(token);

            var handler = new JwtSecurityTokenHandler();
            var act = () => handler.ValidateToken(tokenString, _validationParams, out _);

            act.Should().Throw<SecurityTokenException>();
        }

        [Fact]
        public void Token_FromForeignSystem_AllDifferent_IsRejected()
        {
            // A completely foreign token: different key, issuer, and audience
            var foreignToken = CreateForeignToken(
                secret: "TotallyDifferentKeyFromACompletelyForeignSystem1234567!!",
                issuer: "EvilService",
                audience: "EvilAudience");

            var handler = new JwtSecurityTokenHandler();
            var act = () => handler.ValidateToken(foreignToken, _validationParams, out _);

            act.Should().Throw<SecurityTokenException>();
        }

        private static string CreateForeignToken(string secret, string issuer, string audience)
        {
            var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(secret));
            var credentials = new SigningCredentials(key, SecurityAlgorithms.HmacSha512);
            var token = new JwtSecurityToken(
                issuer: issuer,
                audience: audience,
                claims: new[]
                {
                    new Claim("Username", "foreignuser"),
                    new Claim("Email", "foreign@evil.com"),
                    new Claim(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString())
                },
                expires: DateTime.UtcNow.AddHours(1),
                signingCredentials: credentials);

            return new JwtSecurityTokenHandler().WriteToken(token);
        }
    }
}
